<?

$GLOBALS["SITE_ID"] = "s3";
$GLOBALS["IBLOCK_TYPE"] = "mn_catalog";
$GLOBALS["CATALOG_GROUP_ID"] = 1;
$GLOBALS["CATALOG_STORE_CODE"] = "MSK";



$GLOBALS["TYPEPREFIX_CODE"] = "TYPEPREFIX";
$GLOBALS["BRAND_CODE"] = "_BRAND";
$GLOBALS["MODEL_CODE"] = "MODEL";
$GLOBALS["ART_CODE"] = "ART";
$GLOBALS["EAN_CODE"] = "EAN_CODE";
$GLOBALS["COUNTRY_CODE"] = "COUNTRY";

$GLOBALS["SITE_NAME"] = 'Liebherr';
$GLOBALS["SITE_COMPANY"] = 'Фирменный магазин Liebherr';
$GLOBALS["SITE_URL"] = 'https://l-rus.ru';
$GLOBALS["YM_TAG"] = 'mn_market';

$GLOBALS["BRANDS_IBLOCK_ID"] = 3;
$GLOBALS["COLORS_IBLOCK_ID"] = 2;
$GLOBALS["CATEGORIES_IBLOCK_ID"] = null;
$GLOBALS["LABELS_IBLOCK_ID"] = 426;

$notShowProp = array(
	"WORDSTAT",	
	"SEARCH_WORD",	
	"TYPE_PREFIX",	
	"YM_DELIVERY",	
	"ANAPA",	
	"SOCHI",	
	"KIROV",	
	"EKBURG",	
	"FAST_DELIVERY",	
	"COMMISSION",	
	"IS_MRC",	
	"ANALOG",	
	"VIDEO2",
	"ACC",
	"_BRAND",
	"FREE_CONNECT",
	"MODEL",
	"_UNID",
	"MSK",
	"SPB",
	"DELIVERY_COST",
	"YM_TYPEPREFIX",
	"YM_VENDOR",
	"YM_VENDORCODE",
	"YM_MODEL",
	"YM_WARRANTY",
	"YM_COUNTRY",
	"SEARCH_INDEX",
	"COMMENT",
	"S_HIT",
	"S_NEW",
	"S_SALE",
);
?>